sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t priest20/react-test -f ./client/Dockerfile.dev ./client

script:
 - docker run -e CI=true priest20/react-test npm test
after_success:
  - docker build -t priest20/multi-client ./client
  - docker build -t priest20/multi-nginx ./nginx
  - docker build -t priest20/multi-server ./server
  - docker build -t priest20/multi-worker ./worker
  - echo "$DOCKER_PASSWORD"  | docker login -u "$DOCKER_ID" --password-stdin
  - docker push priest20/multi-client
  - docker push priest20/multi-nginx
  - docker push priest20/multi-server
  - docker push priest20/multi-worker